apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: vc01cl01-t0compute
