FROM jenkins/inbound-agent:latest-jdk17

USER root
# RUN commands
RUN set -x; apt-get update \
  && apt-get install --no-install-recommends -y \
    ca-certificates \
    curl \
    gpg

# RUN mkdir -p /etc/apt/keyrings
# RUN curl -fsSL https://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub | gpg --dearmor -o /etc/apt/keyrings/tanzu-archive-keyring.gpg
# RUN echo "deb [signed-by=/etc/apt/keyrings/tanzu-archive-keyring.gpg] https://storage.googleapis.com/tanzu-cli-os-packages/apt tanzu-cli-jessie main" | tee /etc/apt/sources.list.d/tanzu.list

# RUN set -x; apt-get update \
#   && apt-get install --no-install-recommends -y \
#     tanzu-cli

# # RUN tanzu config set env.TANZU_CLI_ADDITIONAL_PLUGIN_DISCOVERY_IMAGES_TEST_ONLY harbor-repo.vmware.com/tanzu_cli_stage/plugins/plugin-inventory:latest
# RUN tanzu config eula accept
# ENV TANZU_CLI_CEIP_OPT_IN_PROMPT_ANSWER no 
# RUN tanzu plugin install --group vmware-tanzu/app-developer

# # USER 1001
